name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        laravel: [^10.0, ^11.0]
        php: [8.1, 8.2, 8.3]
        include:
          - laravel: 11.*
            testbench: 9.*
          - laravel: 10.*
            testbench: 8.*
        exclude:
          - laravel: 11.*
            php: 8.1

    name: PHP v${{ matrix.php }} - Laravel v${{ matrix.laravel }}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extension: mbstring, pdo, pdo_sqlite
          coverage: none

      - name: Install dependencies
        run: |
          composer require "illuminate/contracts:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer install --prefer-dist --no-interaction --no-suggest

      - name: Run tests
        run: vendor/bin/pest
